###
GET http://localhost:3000/api/v1/aspiration-addresses

###
curl -X POST http://localhost:3000/api/v1/aspiration-addresses \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWlubiIsInVzZXJfaWQiOiI4Zjk2YmM4ZC00YzI1LTQzOTgtYjM3Mi1iOGI4MGIwNjEzNTUiLCJ1c2VyX3JvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzUxMzM2MSwiZXhwIjoxNzE3NTU2NTYxfQ._46xhxkRTrGWEDtA0Z-av9V_fKxjVO5N4fVffo127is" \
-H "Content-Type: application/json" \
-d '{"aspiration_address": "Staf3"}'

###
curl -X GET http://localhost:3000/api/v1/aspiration-addresses/f6dbef09-5750-4ac9-a161-ec8f99d43609 \

###
curl -X PATCH http://localhost:3000/api/v1/aspiration-addresses/f6dbef09-5750-4ac9-a161-ec8f99d43609 \
-H "Content-Type: application/json" \
-d '{"aspiration_address": "Staf Admin"}'

###
DELETE http://localhost:3000/api/v1/aspiration-addresses/83e648bd-6d7e-4b39-86be-0bf3abd52a29
 