###
GET http://localhost:3000/api/v1/aspiration-addresses

###
curl -X POST http://localhost:3000/api/v1/aspiration-addresses \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmciLCJ1c2VyX2lkIjoiYTA1NzAwOWQtM2IyZS00ODYyLTk3ZjQtM2I3YzBkMzViNzg5IiwidXNlcl9yb2xlIjoic3R1ZGVudHMiLCJpYXQiOjE3MTczMTk1ODksImV4cCI6MTcxNzMyMTM4OX0.xXN03F1BXD2ZTp4OSUa9OQFlzJDIJhTMF25LifJ6ZNs" \
-H "Content-Type: application/json" \
-d '{"aspiration_address": "Staf"}'

###
curl -X GET http://localhost:3000/api/v1/aspiration-addresses/f6dbef09-5750-4ac9-a161-ec8f99d43609 \

###
curl -X PATCH http://localhost:3000/api/v1/aspiration-addresses/f6dbef09-5750-4ac9-a161-ec8f99d43609 \
-H "Content-Type: application/json" \
-d '{"aspiration_address": "Staf Admin"}'

###
DELETE http://localhost:3000/api/v1/aspiration-addresses/f6dbef09-5750-4ac9-a161-ec8f99d43609
 