###
GET http://localhost:3000/api/v1/aspiration
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWlubiIsInVzZXJfaWQiOiI4Zjk2YmM4ZC00YzI1LTQzOTgtYjM3Mi1iOGI4MGIwNjEzNTUiLCJ1c2VyX3JvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzU3NTM4NywiZXhwIjoxNzE3NjE4NTg3fQ.C2LwwmDoKEAvi6Sk6gJSMsFOwS3bGmhvOLpaguvOqAY

###
curl -X POST http://localhost:3000/api/v1/aspiration/create \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWlubiIsInVzZXJfaWQiOiI4Zjk2YmM4ZC00YzI1LTQzOTgtYjM3Mi1iOGI4MGIwNjEzNTUiLCJ1c2VyX3JvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzUyMTM1MywiZXhwIjoxNzE3NTY0NTUzfQ.BNAc5DpBYjjxTJCTQfuqI9ryFjPOePiSFECDAVqdFBY" \
-H "Content-Type: application/json" \
-d '{
  "aspiration": "Cara jadi ketua himpunan???",
  "user_id": "1c435668-66a9-468c-a40b-6d9ccea87344",
  "aspiration_address_id": "a05c7ccd-68e6-467f-b8b9-a54c145281fe"
}'

###

GET http://localhost:3000/api/v1/aspiration/00735b82-f4da-4899-8124-c35b0c37087e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWlubiIsInVzZXJfaWQiOiI4Zjk2YmM4ZC00YzI1LTQzOTgtYjM3Mi1iOGI4MGIwNjEzNTUiLCJ1c2VyX3JvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzU3NTM4NywiZXhwIjoxNzE3NjE4NTg3fQ.C2LwwmDoKEAvi6Sk6gJSMsFOwS3bGmhvOLpaguvOqAY



###
GET http://localhost:3000/api/v1/aspiration/user/johndoe


###
curl -X PATCH http://localhost:3000/api/v1/aspiration/00735b82-f4da-4899-8124-c35b0c37087e \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWlubiIsInVzZXJfaWQiOiI4Zjk2YmM4ZC00YzI1LTQzOTgtYjM3Mi1iOGI4MGIwNjEzNTUiLCJ1c2VyX3JvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzU3NTM4NywiZXhwIjoxNzE3NjE4NTg3fQ.C2LwwmDoKEAvi6Sk6gJSMsFOwS3bGmhvOLpaguvOqAY" \
-H "Content-Type: application/json" \
-d '{
  "aspiration": "Cara jadi ketua himpunan test 1???",
  "user_id": "1c435668-66a9-468c-a40b-6d9ccea87344",
  "aspiration_address_id": "a05c7ccd-68e6-467f-b8b9-a54c145281fe"
}'

### Admin
PATCH http://localhost:3000/api/v1/aspiration/status/7e7fac58-499b-4ba8-b707-5c68898947e2 \
Content-Type: application/json

{
  "aspiration_status": "rejected" 
}'

#aspiration_status (pending, approved, rejected)

###
DELETE http://localhost:3000/api/v1/aspiration/fa7953ec-c1c6-4572-8dd5-704a18e6f3e7