###
GET http://localhost:3000/api/v1/candidates

###
GET http://localhost:3000/api/v1/candidates/john-doe

###
POST http://localhost:3000/api/v1/candidates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWlubiIsInVzZXJfaWQiOiI4Zjk2YmM4ZC00YzI1LTQzOTgtYjM3Mi1iOGI4MGIwNjEzNTUiLCJ1c2VyX3JvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzUwOTQ3MCwiZXhwIjoxNzE3NTEzMDcwfQ.-o4fzV_kohKDVXfLgFCm60nwPPzkKfWj5ErC42SFVpE
Content-Type: application/json

{
  "candidate_name": "John 2",
  "candidate_biography": "John Doe has a rich background in community service and leadership.",
  "candidate_vision": "To create a more inclusive and prosperous community for all.",
  "candidate_mission": "To implement policies that promote economic growth, education, and social justice."
}

###
PATCH http://localhost:3000/api/v1/candidates/c163d5e2-b4d0-4b97-ae35-549c7a77b766
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV3aW5nIiwidXNlcl9pZCI6ImVhOTA2MWQ4LTUxOGQtNDk2ZS1iODcxLTRjOGVlYTVlNTdiOSIsInVzZXJfcm9sZSI6InN0dWRlbnRzIiwiaWF0IjoxNzE3MzQ0MTQwLCJleHAiOjE3MTczNDU5NDB9.CAIq3XyEYDFn9iUlyzeaTFstM_O59QU66on5jXvCr9Q
Content-Type: application/json

{
  "candidate_name": "john doe",
  "candidate_biography": "John Doe has a rich background in community service and leadership.",
  "candidate_vision": "To create a more inclusive and prosperous community for all.",
  "candidate_mission": "To implement policies that promote economic growth, education, and social justice."
}

###
DELETE http://localhost:3000/api/v1/candidates/c163d5e2-b4d0-4b97-ae35-549c7a77b766
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV3aW5nIiwidXNlcl9pZCI6ImVhOTA2MWQ4LTUxOGQtNDk2ZS1iODcxLTRjOGVlYTVlNTdiOSIsInVzZXJfcm9sZSI6InN0dWRlbnRzIiwiaWF0IjoxNzE3Mzc3MDY4LCJleHAiOjE3MTczNzg4Njh9.lCfcj6jD-13kPbzJD0_q3VlWBQT1W2irvJgDQYoJX9k