###
GET http://localhost:3000/api/v1/candidates

###
GET http://localhost:3000/api/v1/candidates/john-doe

###
POST http://localhost:3000/api/v1/candidates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmciLCJ1c2VyX2lkIjoiYTA1NzAwOWQtM2IyZS00ODYyLTk3ZjQtM2I3YzBkMzViNzg5IiwidXNlcl9yb2xlIjoic3R1ZGVudHMiLCJpYXQiOjE3MTczMTU1MDUsImV4cCI6MTcxNzMxNzMwNX0.wsGydehRVYCooud98TfIxb7Ef5rKIaa_YY8R90u5Iwk
Content-Type: application/json

{
  "candidate_name": "John Doe",
  "candidate_biography": "John Doe has a rich background in community service and leadership.",
  "candidate_vision": "To create a more inclusive and prosperous community for all.",
  "candidate_mission": "To implement policies that promote economic growth, education, and social justice."
}

###
PATCH http://localhost:3000/api/v1/candidates/c163d5e2-b4d0-4b97-ae35-549c7a77b766
Content-Type: application/json

{
  "candidate_name": "john doe",
  "candidate_biography": "John Doe has a rich background in community service and leadership.",
  "candidate_vision": "To create a more inclusive and prosperous community for all.",
  "candidate_mission": "To implement policies that promote economic growth, education, and social justice."
}

###
DELETE http://localhost:3000/api/v1/candidates/c163d5e2-b4d0-4b97-ae35-549c7a77b766