
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhbmR5IiwidXNlcl9pZCI6IjNlNzFkYTdhLWNiYTItNDJjZC05Y2UwLWM2MWQwNjdlNGRjNSIsInVzZXJfcm9sZSI6InN0dWRlbnRzIiwiaWF0IjoxNzE3ODQ0MTA5LCJleHAiOjE3MTc4NDQxMjl9.aKihKzftNpEA4qzxHW7AQZAAL13-Io6z7SD9TaTmeG4

{
  "username": "ewingg",
  "user_email": "ewingg@mail.com",
  "user_password": "ewing123",
  "user_attempt": 1
}

### 
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "username": "ewingg",
  "user_password": "ewing123"
}

###
POST http://localhost:3000/api/v1/users/access-token 
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV3aW5nIiwidXNlcl9pZCI6ImVhOTA2MWQ4LTUxOGQtNDk2ZS1iODcxLTRjOGVlYTVlNTdiOSIsInVzZXJfcm9sZSI6ImFkbWluIiwiaWF0IjoxNzE3NTcwMTI5LCJleHAiOjE3MTc4MjkzMjl9.aw3sUwnynf5cFI6V-G_Q26l_gzp9Ry66RT1sD7ewRAE"
}

###
POST http://localhost:3000/api/v1/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV3aW5nIiwidXNlcl9pZCI6ImVhOTA2MWQ4LTUxOGQtNDk2ZS1iODcxLTRjOGVlYTVlNTdiOSIsInVzZXJfcm9sZSI6ImFkbWluIiwiaWF0IjoxNzE3NDI2OTEyLCJleHAiOjE3MTc0MjY5MjJ9.KBZbUwHs1-5qR_bzY4CLcHoAcPgLXMzb4Ix4nNt2vv0



