
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json

{
  "username": "randy",
  "user_email": "rcwjys@example.com",
  "user_password": "rcwjys",
  "user_attempt": 1
}

### 
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "username": "ewing",
  "user_password": "ewing123"
}

###
POST http://localhost:3000/api/v1/users/access-token 
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV3aW5nIiwidXNlcl9pZCI6ImVhOTA2MWQ4LTUxOGQtNDk2ZS1iODcxLTRjOGVlYTVlNTdiOSIsInVzZXJfcm9sZSI6ImFkbWluIiwiaWF0IjoxNzE3NDI1MjEzLCJleHAiOjE3MTc2ODQ0MTN9.ll3HeKJwvgWTznQjjuGPGYHvTtH_nfUfuSWqPAxbdvo"
}

###
POST http://localhost:3000/api/v1/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV3aW5nIiwidXNlcl9pZCI6ImVhOTA2MWQ4LTUxOGQtNDk2ZS1iODcxLTRjOGVlYTVlNTdiOSIsInVzZXJfcm9sZSI6ImFkbWluIiwiaWF0IjoxNzE3NDI2OTEyLCJleHAiOjE3MTc0MjY5MjJ9.KBZbUwHs1-5qR_bzY4CLcHoAcPgLXMzb4Ix4nNt2vv0



