GET http://localhost:3000/api/v1/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJ1c2VyX2lkIjoiMDg4MWFhYzgtYWJlOC00N2EyLTkyN2UtODRhY2NjNGZlNTMxIiwidXNlcl9yb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTcxMzE3MjksImV4cCI6MTcxNzEzMzUyOX0.Q6F4Cq9nNbumB1EUtev5yNZmFrlF9LzxOPLXFhTtMuQ

###
GET http://localhost:3000/api/v1/votes/d10114f4-fa01-4ab9-93e5-50e37f226e44

###
POST http://localhost:3000/api/v1/votes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmciLCJ1c2VyX2lkIjoiYTA1NzAwOWQtM2IyZS00ODYyLTk3ZjQtM2I3YzBkMzViNzg5IiwidXNlcl9yb2xlIjoic3R1ZGVudHMiLCJpYXQiOjE3MTczMjUwNDUsImV4cCI6MTcxNzMyNjg0NX0.ZOY4_wPrflFYxSu3m5VmbFJilSBrp5gD1_4MxJZSOnk

{
  "candidate_id": "92902c50-3078-45aa-b1a0-9f75e00923db",
  "voter_name": "ming"
}

###
DELETE http://localhost:3000/api/v1/votes/daa5fb68-cef2-4d45-911e-0511d34d280b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJ1c2VyX2lkIjoiMDg4MWFhYzgtYWJlOC00N2EyLTkyN2UtODRhY2NjNGZlNTMxIiwidXNlcl9yb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTcxMzE3MjksImV4cCI6MTcxNzEzMzUyOX0.Q6F4Cq9nNbumB1EUtev5yNZmFrlF9LzxOPLXFhTtMuQ