GET http://localhost:3000/api/v1/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhbmR5IiwidXNlcl9pZCI6IjNlNzFkYTdhLWNiYTItNDJjZC05Y2UwLWM2MWQwNjdlNGRjNSIsInVzZXJfcm9sZSI6InN0dWRlbnRzIiwiaWF0IjoxNzE3ODQ0Mjg3LCJleHAiOjE3MTc4NDQzMDd9.SmE9On8dzTeSHpBQZDZ2_8uYCjXN41r2a5KaUrBxA2o

###
GET http://localhost:3000/api/v1/votes/d10114f4-fa01-4ab9-93e5-50e37f226e44

###
POST http://localhost:3000/api/v1/votes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV3aW5nZyIsInVzZXJfaWQiOiI2NzQwMWUxMS03MjM3LTRjZGUtYTYyYi02NGVlNGY4NmJhNjEiLCJ1c2VyX3JvbGUiOiJzdHVkZW50cyIsImlhdCI6MTcxODAwMzc4MSwiZXhwIjoxNzE4MDA2NDgxfQ._WnlKMjO_iFMtnGWY-sCHKK11Ha--euU_l7IuRpzsKk

{
  "user_id": "67401e11-7237-4cde-a62b-64ee4f86ba61",
  "candidate_id": "5cba782f-317a-4ab3-9cfa-305031a7fe5d"

}

###
DELETE http://localhost:3000/api/v1/votes/1f12d5af-6050-490d-b2ff-6c0c85f333ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV3aW5nIiwidXNlcl9pZCI6ImVhOTA2MWQ4LTUxOGQtNDk2ZS1iODcxLTRjOGVlYTVlNTdiOSIsInVzZXJfcm9sZSI6ImFkbWluIiwiaWF0IjoxNzE3NDA4ODg5LCJleHAiOjE3MTc0MTA2ODl9.QLs0dJk2DTKFoouymBKPT7_uWZZTtEK45LFg-38bmZU